name: lions
description: Lions Club.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rxdart: ^0.18.0
  http: ^0.13.0
  http_interceptor: ^0.4.0
  url_launcher: ^6.1.5
  intl: ^0.17.0
  toggle_switch: "^0.1.9"
  #flutter_otp_text_field: ^0.0.1+1
  pin_code_fields: ^7.2.0
  auto_size_text: ^2.1.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^10.0.2
  firebase_core: any
  syncfusion_flutter_pdf: ^20.2.49
  open_file: ^3.2.1
  path_provider: ^2.0.11
  #flutter_local_notifications: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
#  flutter_rename_app: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/international_con.png"
  remove_alpha_ios: true
  #image_path_android: "assets/images/lions_logo.png"
  #image_path_ios: "assets/images/lions_logo.png"
  adaptive_icon_background: "#132290" # "assets/images/lions_logo.png"
  #adaptive_icon_foreground: "assets/images/lions_logo.png"

#flutter_rename_app:
#  applicaton_name: Lions
#  dart_package_name: lions
#  application_id: com.ces.lions
#  bundle_id: com.ces.lions
#  android_package_name: com.ces.lions
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/placeholder.png
    - assets/images/international_logo.png
    - assets/images/international_logo2.png
    - assets/images/lions_logo.png
    - assets/images/international.png
    - assets/images/district.png
    - assets/images/zone.png
    - assets/images/city.png
    - assets/images/region.png
    - assets/images/dg-team.png
    - assets/images/multiple.png
    - assets/images/past-governers.png
    - assets/images/cabinet.png
    - assets/images/mjf-members.png
    - assets/images/clubs.png
    - assets/images/close.png
    - assets/images/international_con.png
    - assets/images/pdf_logo.png
  #  - assets/images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
